#!/bin/sh

set -e

I=nix-dev-install

#echo "$I: Copying current configuration to nix-dev dir"
#cp /etc/nixos/configuration.nix current-configuration.nix
#ln -s current-configuration.nix nixos-config

echo "$I: Checking out nixpkgs tree"
git clone https://github.com/NixOS/nixpkgs

echo "$I: Creating 'local' branches for development"

( cd nixpkgs
  git branch local
  git checkout local
)

echo ""
echo "Consider adding following lines to your .bashrc:"
echo ""
echo ">"
echo "> export NIX_DEV_ROOT=`pwd`"
echo "> . `pwd`/nixrc"
echo ">"

