#!/bin/sh

I=nix-dev-install-grwlf
ME=grwlf

checkout_my_tree() { (
	local tree=$1
	cd $tree
  echo "$I: Adding new remote named 'github' for $tree"
	git remote add github git@github.com:$ME/${tree}.git ||
  git remote set-url github git@github.com:$ME/${tree}.git
  if git branch | grep -qw local ; then
    echo "$I: Backing up 'local' branch into 'old-local'"
    git branch old-local
    git checkout master
    git branch -D local
  fi
  echo "$I: Fetching new local branch from git@github.com:$ME/${tree}.git"
	git fetch -f github +local:local
  echo "$I: Checking out local branch"
	git checkout local
) }

set -e

./install 

checkout_my_tree nixpkgs
checkout_my_tree nixos

